### PR TITLE
Add ILIKE operator

### PR DESCRIPTION
**Pull request by zyla**

### CODE REVIEW

**Comment by meteficha** [comment]
Which RDBMSs besides PostgreSQL support `ILIKE`?  Please document them on `ilike`.

**Comment by meteficha** [comment]
Sorry, hit the wrong button.

**Comment by zyla** [comment]
As far as I know, only PostgreSQL (of those supported by Esqueleto tests). I've changed the commit to document that.

**Comment by meteficha** [comment]
Thanks, released as `esqueleto-2.2.3`.

**Pull request merged**
