### PR TITLE
Implemented support for composite/custom primary keys

### PR DESCRIPTION
**Pull request by albertov**
See discussion @ #87

### CODE REVIEW

**Comment by albertov** [comment]
@meteficha Any ideas on how could Esqueleto be modified to support returning a composite key from a query? Perhaps it could be left unimplemented but at least support returning entities and using composite keys on expressions.

**Comment by andrewthad** [comment]
The branch to refactor persistent has been merged in. So, this will need to depend on persistent >= 2.1.1.7 but it should now be possible to merge it in. @meteficha Do you have any concerns, or can it be merged in?

**Comment by meteficha** [comment]
Sorry for letting this issue linger for so long, @albertov. I'm merging this right now after applying some of my own small cleanups.

**Comment by meteficha** [comment]
Thanks, @albertov, looks awesome!  Merged and released as `esqueleto-2.1.3`.

**Comment by albertov** [comment]
Great, Thanks!

**Pull request merged**
