### PR TITLE
Add `ToBaseId`

### PR DESCRIPTION
**Pull request by pseudonom**
I couldn't put `toBaseId` inside `Esqueleto` because that would have created a cyclic dependency.

### CODE REVIEW

**Comment by meteficha** [comment]
Does it need a cyclic dependency even when translating the type signature from `SqlExpr` to `expr`, etc?

**Comment by pseudonom** [comment]
I believe `veryUnsafe...` forces `SqlExpr` rather than `expr` on us.

**Comment by meteficha** [comment]
But that would be part of the implementation that lives on the class instance, right?

**Comment by pseudonom** [comment]
Ah, yup.

**Comment by pseudonom** [comment]
Amended. Should `ToBaseId` get exported in `Database.Esqueleto` to?

**Comment by meteficha** [comment]
Yes, one can't really use one without the other.

**Comment by pseudonom** [comment]
kk, wasn't exactly sure what your `Internal` policy was.

**Comment by pseudonom** [comment]
This good to go? Can you just drop https://github.com/pseudonom/esqueleto/commit/a104b30da2494b9258f5575c62b2d43957be41b1 when you merge it?

**Comment by meteficha** [comment]
Released as `esqueleto-2.4.3`, thanks!

**Comment by pseudonom** [comment]
Great! Thanks.

**Pull request merged**
